steps:
- name: node:12
  entrypoint: npm
  args: ['install']
- name: node:12
  entrypoint: npm
  args: ['run', 'build']
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://www.fitupyourstyle.com"]